// <auto-generated />
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(BackendContext))]
    [Migration("20240131133854_Third")]
    partial class Third
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Client", b =>
                {
                    b.Property<int>("client_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("client_Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("client_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("client_Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Backend.Models.Client_Account", b =>
                {
                    b.Property<int>("client_account_Id")
                        .HasColumnType("int");

                    b.Property<string>("client_account_Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("client_account_Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("client_account_Id");

                    b.ToTable("Client_Accounts");
                });

            modelBuilder.Entity("Backend.Models.Order", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "ClientId");

                    b.HasIndex("ClientId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("Backend.Models.Product", b =>
                {
                    b.Property<int>("product_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("product_Id"));

                    b.Property<int>("price")
                        .HasColumnType("int");

                    b.Property<string>("product_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sellerId")
                        .HasColumnType("int");

                    b.Property<int>("units")
                        .HasColumnType("int");

                    b.HasKey("product_Id");

                    b.HasIndex("sellerId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Backend.Models.Seller", b =>
                {
                    b.Property<int>("seller_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("seller_Id"));

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("seller_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("seller_Id");

                    b.ToTable("Sellers");
                });

            modelBuilder.Entity("Backend.Models.Seller_Account", b =>
                {
                    b.Property<int>("seller_account_Id")
                        .HasColumnType("int");

                    b.Property<string>("seller_account_Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("seller_account_Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("seller_account_Id");

                    b.ToTable("Seller_Accounts");
                });

            modelBuilder.Entity("Backend.Models.Client_Account", b =>
                {
                    b.HasOne("Backend.Models.Client", "Client")
                        .WithOne("Account")
                        .HasForeignKey("Backend.Models.Client_Account", "client_account_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Backend.Models.Order", b =>
                {
                    b.HasOne("Backend.Models.Client", "Client")
                        .WithMany("Orders")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Product", "Product")
                        .WithMany("Orders")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Backend.Models.Product", b =>
                {
                    b.HasOne("Backend.Models.Seller", "Seller")
                        .WithMany("products")
                        .HasForeignKey("sellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("Backend.Models.Seller_Account", b =>
                {
                    b.HasOne("Backend.Models.Seller", "Seller")
                        .WithOne("Account")
                        .HasForeignKey("Backend.Models.Seller_Account", "seller_account_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("Backend.Models.Client", b =>
                {
                    b.Navigation("Account");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Backend.Models.Product", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Backend.Models.Seller", b =>
                {
                    b.Navigation("Account");

                    b.Navigation("products");
                });
#pragma warning restore 612, 618
        }
    }
}
